use_frameworks!

target 'JGHybrid_Example' do
  pod 'JGHybrid', :path => '../'
  pod "Reveal-SDK","4", :configurations => ["Debug"]
  pod "JGNavigationBarTransition", :path => "../../JGNavigationBarTransition"

  target 'JGHybrid_Tests' do
    inherit! :search_paths
    
  end
end
